version: '3'

services:
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_DB: product_list_db         
      POSTGRES_USER: user                  
      POSTGRES_PASSWORD: password          
    ports:
      - "5432:5432"                        
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - app-network
  
  backend:
    build:
      context: .                         
      dockerfile: Dockerfile             
    ports:
      - "3333:3333"                    
    volumes:
      - .:/usr/src/app                   
    environment:
      DB_HOST: db                        
      DB_PORT: 5432                      
      DB_USER: user                      
      DB_PASSWORD: password              
      DB_NAME: api_vendas_db             
    depends_on:
      - db                               
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
