version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: product_list_db         
      POSTGRES_USER: user                  
      POSTGRES_PASSWORD: password          
    ports:
      - "5432:5432"                        
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  backend:
    build:
      context: .                         
      dockerfile: Dockerfile             
    ports:
      - "3333:3333"                    
    volumes:
      - .:/usr/src/app                   
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/product_list_db?schema=public
    depends_on:
      - db                               
    networks:
      - app-network

volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge
